version: '3'
services:
  msfs:
    # 攻击平台-渗透工具部署，保持同一网段方便通信
    image: linuxkonsult/kali-metasploit
    tty: true  # 启动失败是因为缺失了控制终端的配置，这里有两种方式修复； 如果不加，msf将会启动失败
    ports:
      - "1234:1234"
    networks:
      app_net:
        ipv4_address: 10.10.10.10
    container_name: "compose-msf"
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    depends_on:
      - "php"
    volumes:
      - "$PWD/conf.d:/etc/nginx/conf.d"
      - "$PWD/html:/usr/share/nginx/html"
    networks:
      - app_net
    container_name: "compose-nginx"
  php:
    build: ./php-mysqli
    image: php:7.2-fpm-mysqli
    ports:
      - "9000:9000"
    volumes:
      - "$PWD/html:/var/www/html"
    networks:
      - app_net
    # depends_on:
    #   - python
    container_name: "compose-php"
  # python:
  #   image: python:3.7-alpine
  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
    networks:
      app_net:
        ipv4_address: 10.10.10.11
    container_name: "compose-mysql"
networks:
  app_net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.10.0/24
